apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: sleep-health-check
spec:
  workloadSelector:
    labels:
      app: sleep
  configPatches:
  - applyTo: CLUSTER
    match:
      context: SIDECAR_OUTBOUND
      cluster:
        service: httpbin.mesh.global
    patch:
      operation: MERGE
      value:
        health_checks:
        - timeout: 10s
          interval: 1s
          always_log_health_check_failures: true
          event_log_path: /dev/stdout
          unhealthy_threshold: 1
          healthy_threshold: 3
          no_traffic_interval: 1s
          http_health_check:
            host: httpbin.mesh.global
            path: /get